Style

diff --git a/bash.d/process.d/start_process_and_create_temp_file b/bash.d/process.d/start_process_and_create_temp_file
--- a/bash.d/process.d/start_process_and_create_temp_file
+++ b/bash.d/process.d/start_process_and_create_temp_file
@@ -4,23 +4,27 @@
 # @since 2015-11-11
 ####
 
-if [[ $# -eq 0 ]]; then
-    echo 'No arguments supplied'
-    echo 'usage:'
-    echo '<command> <path to executable> [<file_name>]'
-    exit 1
-fi
+function _main() {
+  if [[ $# -eq 0 ]]; then
+      echo 'Error: No arguments supplied!'
+      echo 'Usage:'
+      echo '   <command> <path to executable> [<file_name>]'
+      exit 1
+  fi
 
-PATH_TO_EXECUTABLE="$1"
+  PATH_TO_EXECUTABLE="${1}"
 
-if [[ $# -gt 1 ]]; then
-    FILE_NAME="$2"
-else
-    FILE_NAME='/tmp/start_process_and_create_temp_file_'$$
-fi
+  if [[ $# -gt 1 ]]; then
+      FILE_NAME="${2}"
+  else
+      FILE_NAME='/tmp/start_process_and_create_temp_file_'$$
+  fi
 
-touch $FILE_NAME
+  touch "${FILE_NAME}"
 
-$($PATH_TO_EXECUTABLE)
+  $(${PATH_TO_EXECUTABLE})
 
-rm $FILE_NAME
+  rm "${FILE_NAME}"
+}
+
+_main "${@}"
